//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ClubCardEF
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class ClubCardDBEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“ClubCardDBEntities”部分中的连接字符串初始化新 ClubCardDBEntities 对象。
        /// </summary>
        public ClubCardDBEntities() : base("name=ClubCardDBEntities", "ClubCardDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ClubCardDBEntities 对象。
        /// </summary>
        public ClubCardDBEntities(string connectionString) : base(connectionString, "ClubCardDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ClubCardDBEntities 对象。
        /// </summary>
        public ClubCardDBEntities(EntityConnection connection) : base(connection, "ClubCardDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MerchantClub> MerchantClub
        {
            get
            {
                if ((_MerchantClub == null))
                {
                    _MerchantClub = base.CreateObjectSet<MerchantClub>("MerchantClub");
                }
                return _MerchantClub;
            }
        }
        private ObjectSet<MerchantClub> _MerchantClub;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 MerchantClub EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMerchantClub(MerchantClub merchantClub)
        {
            base.AddObject("MerchantClub", merchantClub);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClubCardDBModel", Name="MerchantClub")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MerchantClub : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MerchantClub 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="orders">Orders 属性的初始值。</param>
        /// <param name="status">Status 属性的初始值。</param>
        /// <param name="addTime">AddTime 属性的初始值。</param>
        /// <param name="updateTime">UpdateTime 属性的初始值。</param>
        /// <param name="merChantName">MerChantName 属性的初始值。</param>
        /// <param name="merChantId">MerChantId 属性的初始值。</param>
        public static MerchantClub CreateMerchantClub(global::System.Int32 id, global::System.Int32 orders, global::System.Int32 status, global::System.DateTime addTime, global::System.DateTime updateTime, global::System.String merChantName, global::System.Int32 merChantId)
        {
            MerchantClub merchantClub = new MerchantClub();
            merchantClub.Id = id;
            merchantClub.Orders = orders;
            merchantClub.Status = status;
            merchantClub.AddTime = addTime;
            merchantClub.UpdateTime = updateTime;
            merchantClub.MerChantName = merChantName;
            merchantClub.MerChantId = merChantId;
            return merchantClub;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CardNum
        {
            get
            {
                return _CardNum;
            }
            set
            {
                OnCardNumChanging(value);
                ReportPropertyChanging("CardNum");
                _CardNum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CardNum");
                OnCardNumChanged();
            }
        }
        private global::System.String _CardNum;
        partial void OnCardNumChanging(global::System.String value);
        partial void OnCardNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Orders
        {
            get
            {
                return _Orders;
            }
            set
            {
                OnOrdersChanging(value);
                ReportPropertyChanging("Orders");
                _Orders = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Orders");
                OnOrdersChanged();
            }
        }
        private global::System.Int32 _Orders;
        partial void OnOrdersChanging(global::System.Int32 value);
        partial void OnOrdersChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AddTime
        {
            get
            {
                return _AddTime;
            }
            set
            {
                OnAddTimeChanging(value);
                ReportPropertyChanging("AddTime");
                _AddTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddTime");
                OnAddTimeChanged();
            }
        }
        private global::System.DateTime _AddTime;
        partial void OnAddTimeChanging(global::System.DateTime value);
        partial void OnAddTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdateTime
        {
            get
            {
                return _UpdateTime;
            }
            set
            {
                OnUpdateTimeChanging(value);
                ReportPropertyChanging("UpdateTime");
                _UpdateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateTime");
                OnUpdateTimeChanged();
            }
        }
        private global::System.DateTime _UpdateTime;
        partial void OnUpdateTimeChanging(global::System.DateTime value);
        partial void OnUpdateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MerChantName
        {
            get
            {
                return _MerChantName;
            }
            set
            {
                OnMerChantNameChanging(value);
                ReportPropertyChanging("MerChantName");
                _MerChantName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MerChantName");
                OnMerChantNameChanged();
            }
        }
        private global::System.String _MerChantName;
        partial void OnMerChantNameChanging(global::System.String value);
        partial void OnMerChantNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MerChantId
        {
            get
            {
                return _MerChantId;
            }
            set
            {
                OnMerChantIdChanging(value);
                ReportPropertyChanging("MerChantId");
                _MerChantId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MerChantId");
                OnMerChantIdChanged();
            }
        }
        private global::System.Int32 _MerChantId;
        partial void OnMerChantIdChanging(global::System.Int32 value);
        partial void OnMerChantIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Extend1
        {
            get
            {
                return _Extend1;
            }
            set
            {
                OnExtend1Changing(value);
                ReportPropertyChanging("Extend1");
                _Extend1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Extend1");
                OnExtend1Changed();
            }
        }
        private global::System.String _Extend1;
        partial void OnExtend1Changing(global::System.String value);
        partial void OnExtend1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Extend2
        {
            get
            {
                return _Extend2;
            }
            set
            {
                OnExtend2Changing(value);
                ReportPropertyChanging("Extend2");
                _Extend2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Extend2");
                OnExtend2Changed();
            }
        }
        private global::System.String _Extend2;
        partial void OnExtend2Changing(global::System.String value);
        partial void OnExtend2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Extend3
        {
            get
            {
                return _Extend3;
            }
            set
            {
                OnExtend3Changing(value);
                ReportPropertyChanging("Extend3");
                _Extend3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Extend3");
                OnExtend3Changed();
            }
        }
        private global::System.String _Extend3;
        partial void OnExtend3Changing(global::System.String value);
        partial void OnExtend3Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OpenId
        {
            get
            {
                return _OpenId;
            }
            set
            {
                OnOpenIdChanging(value);
                ReportPropertyChanging("OpenId");
                _OpenId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OpenId");
                OnOpenIdChanged();
            }
        }
        private global::System.String _OpenId;
        partial void OnOpenIdChanging(global::System.String value);
        partial void OnOpenIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserNickName
        {
            get
            {
                return _UserNickName;
            }
            set
            {
                OnUserNickNameChanging(value);
                ReportPropertyChanging("UserNickName");
                _UserNickName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserNickName");
                OnUserNickNameChanged();
            }
        }
        private global::System.String _UserNickName;
        partial void OnUserNickNameChanging(global::System.String value);
        partial void OnUserNickNameChanged();

        #endregion

    
    }

    #endregion

    
}
