//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Dos.Model
{

	/// <summary>
	/// 实体类Activity 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Activity")]
	[Serializable]
	public partial class Activity : Entity 
	{
		#region Model
		private int _ID;
		private string _Title;
		private string _Entitle;
		private string _Conver;
		private string _Description;
		private string _Contents;
		private DateTime _AddTime;
		private DateTime _UpdateTime;
		private int _Orders;
		private int _Status;
		private string _Extend;
		private string _Extend1;
		private int _Type;
		private DateTime _StartTime;
		private DateTime _EndTime;
		private string _Author;
		private string _UpdateAuthor;
		/// <summary>
		/// 
		/// </summary>
		public int ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange(_.ID,_ID,value);
				this._ID=value;
			}
		}
		/// <summary>
		/// 标题
		/// </summary>
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title=value;
			}
		}
		/// <summary>
		/// 英文标题
		/// </summary>
		public string Entitle
		{
			get{ return _Entitle; }
			set
			{
				this.OnPropertyValueChange(_.Entitle,_Entitle,value);
				this._Entitle=value;
			}
		}
		/// <summary>
		/// 封面图
		/// </summary>
		public string Conver
		{
			get{ return _Conver; }
			set
			{
				this.OnPropertyValueChange(_.Conver,_Conver,value);
				this._Conver=value;
			}
		}
		/// <summary>
		/// 描述
		/// </summary>
		public string Description
		{
			get{ return _Description; }
			set
			{
				this.OnPropertyValueChange(_.Description,_Description,value);
				this._Description=value;
			}
		}
		/// <summary>
		/// 正文
		/// </summary>
		public string Contents
		{
			get{ return _Contents; }
			set
			{
				this.OnPropertyValueChange(_.Contents,_Contents,value);
				this._Contents=value;
			}
		}
		/// <summary>
		/// 添加时间
		/// </summary>
		public DateTime AddTime
		{
			get{ return _AddTime; }
			set
			{
				this.OnPropertyValueChange(_.AddTime,_AddTime,value);
				this._AddTime=value;
			}
		}
		/// <summary>
		/// 修改时间
		/// </summary>
		public DateTime UpdateTime
		{
			get{ return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange(_.UpdateTime,_UpdateTime,value);
				this._UpdateTime=value;
			}
		}
		/// <summary>
		/// 排序
		/// </summary>
		public int Orders
		{
			get{ return _Orders; }
			set
			{
				this.OnPropertyValueChange(_.Orders,_Orders,value);
				this._Orders=value;
			}
		}
		/// <summary>
		/// _0-当前状态，1-过期
		/// </summary>
		public int Status
		{
			get{ return _Status; }
			set
			{
				this.OnPropertyValueChange(_.Status,_Status,value);
				this._Status=value;
			}
		}
		/// <summary>
		/// 扩展
		/// </summary>
		public string Extend
		{
			get{ return _Extend; }
			set
			{
				this.OnPropertyValueChange(_.Extend,_Extend,value);
				this._Extend=value;
			}
		}
		/// <summary>
		/// 扩展
		/// </summary>
		public string Extend1
		{
			get{ return _Extend1; }
			set
			{
				this.OnPropertyValueChange(_.Extend1,_Extend1,value);
				this._Extend1=value;
			}
		}
		/// <summary>
		/// _1-圈层活动，2-楼盘活动
		/// </summary>
		public int Type
		{
			get{ return _Type; }
			set
			{
				this.OnPropertyValueChange(_.Type,_Type,value);
				this._Type=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime StartTime
		{
			get{ return _StartTime; }
			set
			{
				this.OnPropertyValueChange(_.StartTime,_StartTime,value);
				this._StartTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime EndTime
		{
			get{ return _EndTime; }
			set
			{
				this.OnPropertyValueChange(_.EndTime,_EndTime,value);
				this._EndTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Author
		{
			get{ return _Author; }
			set
			{
				this.OnPropertyValueChange(_.Author,_Author,value);
				this._Author=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string UpdateAuthor
		{
			get{ return _UpdateAuthor; }
			set
			{
				this.OnPropertyValueChange(_.UpdateAuthor,_UpdateAuthor,value);
				this._UpdateAuthor=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.ID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.Title,
				_.Entitle,
				_.Conver,
				_.Description,
				_.Contents,
				_.AddTime,
				_.UpdateTime,
				_.Orders,
				_.Status,
				_.Extend,
				_.Extend1,
				_.Type,
				_.StartTime,
				_.EndTime,
				_.Author,
				_.UpdateAuthor};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._Title,
				this._Entitle,
				this._Conver,
				this._Description,
				this._Contents,
				this._AddTime,
				this._UpdateTime,
				this._Orders,
				this._Status,
				this._Extend,
				this._Extend1,
				this._Type,
				this._StartTime,
				this._EndTime,
				this._Author,
				this._UpdateAuthor};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Activity");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID","Activity","ID");
			/// <summary>
			/// 标题
			/// </summary>
			public readonly static Field Title = new Field("Title","Activity","标题");
			/// <summary>
			/// 英文标题
			/// </summary>
			public readonly static Field Entitle = new Field("Entitle","Activity","英文标题");
			/// <summary>
			/// 封面图
			/// </summary>
			public readonly static Field Conver = new Field("Conver","Activity","封面图");
			/// <summary>
			/// 描述
			/// </summary>
			public readonly static Field Description = new Field("Description","Activity","描述");
			/// <summary>
			/// 正文
			/// </summary>
			public readonly static Field Contents = new Field("Contents","Activity","正文");
			/// <summary>
			/// 添加时间
			/// </summary>
			public readonly static Field AddTime = new Field("AddTime","Activity","添加时间");
			/// <summary>
			/// 修改时间
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime","Activity","修改时间");
			/// <summary>
			/// 排序
			/// </summary>
			public readonly static Field Orders = new Field("Orders","Activity","排序");
			/// <summary>
			/// _0-当前状态，1-过期
			/// </summary>
			public readonly static Field Status = new Field("Status","Activity","_0-当前状态，1-过期");
			/// <summary>
			/// 扩展
			/// </summary>
			public readonly static Field Extend = new Field("Extend","Activity","扩展");
			/// <summary>
			/// 扩展
			/// </summary>
			public readonly static Field Extend1 = new Field("Extend1","Activity","扩展");
			/// <summary>
			/// _1-圈层活动，2-楼盘活动
			/// </summary>
			public readonly static Field Type = new Field("Type","Activity","_1-圈层活动，2-楼盘活动");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StartTime = new Field("StartTime","Activity","StartTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EndTime = new Field("EndTime","Activity","EndTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Author = new Field("Author","Activity","Author");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdateAuthor = new Field("UpdateAuthor","Activity","UpdateAuthor");
		}
		#endregion


	}
}

