//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Dos.Model
{

	/// <summary>
	/// 实体类Forms 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Forms")]
	[Serializable]
	public partial class Forms : Entity 
	{
		#region Model
		private int _Id;
		private string _Title;
		private int _FormType;
		private string _Name;
		private int? _Number;
		private string _Mobile;
		private int? _Age;
		private string _Source;
		private string _Income;
		private string _Remark;
		private DateTime _AddTime;
		private int _Status;
		private int _Orders;
		private DateTime _UpdateTime;
		private string _Extend;
		private string _Extend2;
		private int _Type;
		private float? _JFCount;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title=value;
			}
		}
		/// <summary>
		/// _0-预约看房,1-
		/// </summary>
		public int FormType
		{
			get{ return _FormType; }
			set
			{
				this.OnPropertyValueChange(_.FormType,_FormType,value);
				this._FormType=value;
			}
		}
		/// <summary>
		/// 姓名
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 人数
		/// </summary>
		public int? Number
		{
			get{ return _Number; }
			set
			{
				this.OnPropertyValueChange(_.Number,_Number,value);
				this._Number=value;
			}
		}
		/// <summary>
		/// 手机号码
		/// </summary>
		public string Mobile
		{
			get{ return _Mobile; }
			set
			{
				this.OnPropertyValueChange(_.Mobile,_Mobile,value);
				this._Mobile=value;
			}
		}
		/// <summary>
		/// 年龄
		/// </summary>
		public int? Age
		{
			get{ return _Age; }
			set
			{
				this.OnPropertyValueChange(_.Age,_Age,value);
				this._Age=value;
			}
		}
		/// <summary>
		/// 来源
		/// </summary>
		public string Source
		{
			get{ return _Source; }
			set
			{
				this.OnPropertyValueChange(_.Source,_Source,value);
				this._Source=value;
			}
		}
		/// <summary>
		/// 收入
		/// </summary>
		public string Income
		{
			get{ return _Income; }
			set
			{
				this.OnPropertyValueChange(_.Income,_Income,value);
				this._Income=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange(_.Remark,_Remark,value);
				this._Remark=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime AddTime
		{
			get{ return _AddTime; }
			set
			{
				this.OnPropertyValueChange(_.AddTime,_AddTime,value);
				this._AddTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int Status
		{
			get{ return _Status; }
			set
			{
				this.OnPropertyValueChange(_.Status,_Status,value);
				this._Status=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int Orders
		{
			get{ return _Orders; }
			set
			{
				this.OnPropertyValueChange(_.Orders,_Orders,value);
				this._Orders=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime UpdateTime
		{
			get{ return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange(_.UpdateTime,_UpdateTime,value);
				this._UpdateTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Extend
		{
			get{ return _Extend; }
			set
			{
				this.OnPropertyValueChange(_.Extend,_Extend,value);
				this._Extend=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Extend2
		{
			get{ return _Extend2; }
			set
			{
				this.OnPropertyValueChange(_.Extend2,_Extend2,value);
				this._Extend2=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int Type
		{
			get{ return _Type; }
			set
			{
				this.OnPropertyValueChange(_.Type,_Type,value);
				this._Type=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public float? JFCount
		{
			get{ return _JFCount; }
			set
			{
				this.OnPropertyValueChange(_.JFCount,_JFCount,value);
				this._JFCount=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.Id;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Title,
				_.FormType,
				_.Name,
				_.Number,
				_.Mobile,
				_.Age,
				_.Source,
				_.Income,
				_.Remark,
				_.AddTime,
				_.Status,
				_.Orders,
				_.UpdateTime,
				_.Extend,
				_.Extend2,
				_.Type,
				_.JFCount};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Title,
				this._FormType,
				this._Name,
				this._Number,
				this._Mobile,
				this._Age,
				this._Source,
				this._Income,
				this._Remark,
				this._AddTime,
				this._Status,
				this._Orders,
				this._UpdateTime,
				this._Extend,
				this._Extend2,
				this._Type,
				this._JFCount};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Forms");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Forms","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Title = new Field("Title","Forms","Title");
			/// <summary>
			/// _0-预约看房,1-
			/// </summary>
			public readonly static Field FormType = new Field("FormType","Forms","_0-预约看房,1-");
			/// <summary>
			/// 姓名
			/// </summary>
			public readonly static Field Name = new Field("Name","Forms","姓名");
			/// <summary>
			/// 人数
			/// </summary>
			public readonly static Field Number = new Field("Number","Forms","人数");
			/// <summary>
			/// 手机号码
			/// </summary>
			public readonly static Field Mobile = new Field("Mobile","Forms","手机号码");
			/// <summary>
			/// 年龄
			/// </summary>
			public readonly static Field Age = new Field("Age","Forms","年龄");
			/// <summary>
			/// 来源
			/// </summary>
			public readonly static Field Source = new Field("Source","Forms","来源");
			/// <summary>
			/// 收入
			/// </summary>
			public readonly static Field Income = new Field("Income","Forms","收入");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Remark = new Field("Remark","Forms","Remark");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AddTime = new Field("AddTime","Forms","AddTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Status = new Field("Status","Forms","Status");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Orders = new Field("Orders","Forms","Orders");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime","Forms","UpdateTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Extend = new Field("Extend","Forms","Extend");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Extend2 = new Field("Extend2","Forms","Extend2");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Type = new Field("Type","Forms","Type");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field JFCount = new Field("JFCount","Forms","JFCount");
		}
		#endregion


	}
}

