//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Dos.Model
{
    /// <summary>
    /// 实体类HdPic。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("HdPic")]
    [Serializable]
    public partial class HdPic : Entity
    {
        #region Model
		private int _Id;
		private string _Name;
		private int _Status;
		private int _Orders;
		private string _PicUrl;
		private DateTime _AddTime;
		private DateTime _UpdateTime;
		private string _Extend1;
		private string _Extend2;
		private string _Extend3;
		private string _Extend4;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange("Name");
				this._Name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int Status
		{
			get{ return _Status; }
			set
			{
				this.OnPropertyValueChange("Status");
				this._Status = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int Orders
		{
			get{ return _Orders; }
			set
			{
				this.OnPropertyValueChange("Orders");
				this._Orders = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PicUrl
		{
			get{ return _PicUrl; }
			set
			{
				this.OnPropertyValueChange("PicUrl");
				this._PicUrl = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime AddTime
		{
			get{ return _AddTime; }
			set
			{
				this.OnPropertyValueChange("AddTime");
				this._AddTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime UpdateTime
		{
			get{ return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange("UpdateTime");
				this._UpdateTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Extend1
		{
			get{ return _Extend1; }
			set
			{
				this.OnPropertyValueChange("Extend1");
				this._Extend1 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Extend2
		{
			get{ return _Extend2; }
			set
			{
				this.OnPropertyValueChange("Extend2");
				this._Extend2 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Extend3
		{
			get{ return _Extend3; }
			set
			{
				this.OnPropertyValueChange("Extend3");
				this._Extend3 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Extend4
		{
			get{ return _Extend4; }
			set
			{
				this.OnPropertyValueChange("Extend4");
				this._Extend4 = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.Name,
				_.Status,
				_.Orders,
				_.PicUrl,
				_.AddTime,
				_.UpdateTime,
				_.Extend1,
				_.Extend2,
				_.Extend3,
				_.Extend4
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._Name,
				this._Status,
				this._Orders,
				this._PicUrl,
				this._AddTime,
				this._UpdateTime,
				this._Extend1,
				this._Extend2,
				this._Extend3,
				this._Extend4
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "HdPic");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "HdPic", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name", "HdPic", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Status = new Field("Status", "HdPic", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Orders = new Field("Orders", "HdPic", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PicUrl = new Field("PicUrl", "HdPic", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AddTime = new Field("AddTime", "HdPic", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime", "HdPic", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Extend1 = new Field("Extend1", "HdPic", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Extend2 = new Field("Extend2", "HdPic", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Extend3 = new Field("Extend3", "HdPic", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Extend4 = new Field("Extend4", "HdPic", "");
        }
        #endregion
	}
}