//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Dos.Model
{
    /// <summary>
    /// 实体类HdPicHit。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("HdPicHit")]
    [Serializable]
    public partial class HdPicHit : Entity
    {
        #region Model
		private int _Id;
		private string _name;
		private string _wxopenid;
		private int _status;
		private int _orders;
		private DateTime _addtime;
		private DateTime _updatetime;
		private string _extend1;
		private string _extend2;
		private int _hdpicid;

		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string name
		{
			get{ return _name; }
			set
			{
				this.OnPropertyValueChange("name");
				this._name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string wxopenid
		{
			get{ return _wxopenid; }
			set
			{
				this.OnPropertyValueChange("wxopenid");
				this._wxopenid = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int status
		{
			get{ return _status; }
			set
			{
				this.OnPropertyValueChange("status");
				this._status = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int orders
		{
			get{ return _orders; }
			set
			{
				this.OnPropertyValueChange("orders");
				this._orders = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime addtime
		{
			get{ return _addtime; }
			set
			{
				this.OnPropertyValueChange("addtime");
				this._addtime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime updatetime
		{
			get{ return _updatetime; }
			set
			{
				this.OnPropertyValueChange("updatetime");
				this._updatetime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string extend1
		{
			get{ return _extend1; }
			set
			{
				this.OnPropertyValueChange("extend1");
				this._extend1 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string extend2
		{
			get{ return _extend2; }
			set
			{
				this.OnPropertyValueChange("extend2");
				this._extend2 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int hdpicid
		{
			get{ return _hdpicid; }
			set
			{
				this.OnPropertyValueChange("hdpicid");
				this._hdpicid = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
		/// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.name,
				_.wxopenid,
				_.status,
				_.orders,
				_.addtime,
				_.updatetime,
				_.extend1,
				_.extend2,
				_.hdpicid,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._name,
				this._wxopenid,
				this._status,
				this._orders,
				this._addtime,
				this._updatetime,
				this._extend1,
				this._extend2,
				this._hdpicid,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "HdPicHit");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "HdPicHit", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field name = new Field("name", "HdPicHit", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field wxopenid = new Field("wxopenid", "HdPicHit", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field status = new Field("status", "HdPicHit", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field orders = new Field("orders", "HdPicHit", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field addtime = new Field("addtime", "HdPicHit", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field updatetime = new Field("updatetime", "HdPicHit", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field extend1 = new Field("extend1", "HdPicHit", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field extend2 = new Field("extend2", "HdPicHit", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field hdpicid = new Field("hdpicid", "HdPicHit", "");
        }
        #endregion
	}
}